apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: colors-virtual-host-ingress
  namespace: colors-ns
  annotations:
    appgw.ingress.kubernetes.io/backend-path-prefix: /
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - host: red.penguintrails.com
    http:
        paths:
        - backend:
                serviceName: red-service
                servicePort: 8080
  - host: green.penguintrails.com
    http:
        paths:
        - backend:
                serviceName: green-service
                servicePort: 8080
  - host: blue.penguintrails.com
    http:
        paths:
        - backend:
                serviceName: blue-service
                servicePort: 8080
  - http:
        paths:
        - backend:
                serviceName: white-service
                servicePort: 8080