apiVersion: apps/v1
kind: Deployment
metadata:
  name: red-deployment
  namespace: colors-ns
  labels:
    app: red
spec:
  replicas: 3
  selector:
    matchLabels:
      app: red
  template:
    metadata:
      labels:
        app: red
    spec:
      containers:
      - name: red-app
        image: hashicorp/http-echo
        args:
        - "-text=red"
        - "-listen=:8080"
       
---
kind: Service
apiVersion: v1
metadata:
  name: red-service
  namespace: colors-ns
spec:
  selector:
    app: red
  ports:
    - port: 8080

